#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www and display information about subdomains
# shellcheck disable=SC2027
# shellcheck disable=SC2086

function get_a_records(){
    if [[ -n "$2" ]]; then
        response="$(dig "$2.$1" | grep -i -A1 "ANSWER SECTION" | tail -n 1)"
        DESTINATION="$(echo "$response" | awk '{ print $5 }')"
        RECORD_TYPE="$(echo "$response" | awk '{ print $4 }')"
        echo  "The subdomain "$2" is a "$RECORD_TYPE" record and points to "$DESTINATION""

    else
        subdomains=(www lb-01 web-01 web-02)
        for SUB_DOMAIN in "${subdomains[@]}"; do
            response="$(dig "$SUB_DOMAIN.$1" | grep -i -A1 "ANSWER SECTION" | tail -n 1)"
            DESTINATION="$(echo ""$response"" | awk '{ print $5 }')"
            RECORD_TYPE="$(echo """$response""" | awk '{ print $4 }')"
            echo "The subdomain ""$SUB_DOMAIN"" is a ""$RECORD_TYPE"" record and points to ""$DESTINATION"""

        done
    fi
}
get_a_records "$1" "$2";
