#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get -y update
sudo apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > sudo tee /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
