#!/usr/bin/env bash
#Fix the container so that Nginx is running as the main process

cd /etc/nginx/sites-enabled/ || exit;
rm -f default;
ln -s /etc/nginx/sites-available/default default;
service nginx restart;
