#!/usr/bin/env bash
#killing a process again (this killed me rather than killing the process)

function sigterm_handler() {
	echo "I am invincible!!!"
	exit 0
}

trap 'sigterm_handler' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
